name: Telegram Story Bot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install FFmpeg & Node.js
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg nodejs

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client isodate yt-dlp telethon requests

      - name: Run Python Script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          COOKIES_TEXT: ${{ secrets.COOKIES_TEXT }}
        run: |
          python main.py
